server:
  port: 19091

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:19092
          predicates:
            - Path=/api/v1/auth/**
          filters:
          #  - StripPrefix=1   # 필요하면 주석 해제

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true


logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

security:
  jwt:
    secret-key: "N2Y5ZDgzNzMwZTU1ODFkMGNhNjE4YzY2YmI3M2ZlYmQ="
    access-token-expire-minutes: 30